New WaveformAnalysisSinc class to interpolate waveforms
rat-pac/ratpac-two pull request #207
Opened 2024-11-26 02:28 UTC by YashBezawada

Added a new `WaveformAnalysisSinc` class (based on the existing WaveformAnalysis class and the WaveformAnalysisLognormal class). 

Updated the `WaveformAnalysisResult` class to include a function `getFOMNames` to get the names of the figures of merit in a waveform analysis. Renamed the function `getFOM` to `getFOMValue`.

Updated the `OutNtupleProc` class to store the figures of merit (FOMs) from a waveform analysis in a root file. In this implementation, you need to add a `waveform_FOMs` field to `IO.ratdb`, to list the names of all the FOMs to be stored in the output root file. For example,  `waveform_FOMs: ["baseline", "chi2ndf", "peak"]`.

2024-11-26 21:00 UTC, JamesJieranShen requested changes
Thanks for the PR! This looks great. I have no issue with the sinc implementation itself. However I think we should discuss a little more about how to implement the FOM readout in the ntuples. I would recommend splitting this into two PRs, one for the sinc fitter and one for the FOM readout.

Note that the comments that I left for the FOM readout are just suggestions on how to implement this, not necessarily asking you to implement the changes yourself;) I'm happy to implement (or help to implement) them. Happy to hear your inputs as well!

Thanks again!

2024-11-26 23:01 UTC, YashBezawada commented on src/io/src/OutNtupleProc.cc
> +#include <memory>
I think this is not necessary now. I was trying different implementations for FOMs and put this in to use unique_ptr. I will remove this.

2024-11-27 23:25 UTC, YashBezawada commented on ratdb/IO.ratdb
> +waveform_FOMs: ["baseline", "chi2ndf", "peak"]
I like the first idea as well. Once can update what to store in a root file without going into the code. Does it also makes sense to move the waveform fitter related parameters from `DIGITIZER_ANALYSIS.ratdb` to the new table?

2024-11-28 07:57 UTC, JamesJieranShen commented on ratdb/IO.ratdb
> +waveform_FOMs: ["baseline", "chi2ndf", "peak"]
Right. I think all information should be consolidated to that table. We should also name it something else now (like `WAVEFORM_ANALYZER.ratdb`).

2024-12-02 22:49 UTC, YashBezawada commented
> Thanks for the PR! This looks great. I have no issue with the sinc implementation itself. However I think we should discuss a little more about how to implement the FOM readout in the ntuples. I would recommend splitting this into two PRs, one for the sinc fitter and one for the FOM readout.
> 
> Note that the comments that I left for the FOM readout are just suggestions on how to implement this, not necessarily asking you to implement the changes yourself;) I'm happy to implement (or help to implement) them. Happy to hear your inputs as well!
> 
> Thanks again!

2024-12-02 22:49 UTC, closed without merging

2024-12-02 22:50 UTC, YashBezawada commented on ratdb/IO.ratdb
> +waveform_FOMs: ["baseline", "chi2ndf", "peak"]
I have closed this pull request and will open two new ones as suggested.